import type { Lang } from "@/types";

export const I18N: Record<Lang, Record<string, string>> = {
  uz: {
    dashboard: "Dashboard",
    warehouse: "Sklad",
    transfers: "Transferlar",
    orders: "Order",
    products: "Mahsulotlar",
    suppliers: "Firmalar",
    logout: "Chiqish",
    language: "Til",
    uzbek: "O'zbek",
    korean: "Koreys",
    dark: "Tungi",
    light: "Kunduzgi",
    mode: "Rejim",
    loading: "Yuklanmoqda...",
    save: "Saqlash",
    cancel: "Bekor qilish",
    close: "Yopish",
    edit: "O'zgartirish",
    view: "Ko'rish",
    approve: "Tasdiqlash",
    reject: "Rad etish",
    sending: "Yuborilmoqda...",
    pending: "Kutilmoqda",
    approved: "Tasdiqlandi",
    rejected: "Rad etildi",
    partial: "Qisman",
    paid: "To'langan",
    unpaid: "To'lanmagan",
    lowStock: "Kam qoldi",
    medium: "O'rtacha",
    good: "Yaxshi",
    searchProduct: "Mahsulot qidirish...",
    noProductsFound: "Mahsulot topilmadi",
    addNewProduct: "Yangi mahsulot qo'shish",
    productName: "Mahsulot nomi",
    category: "Kategoriya",
    unit: "Birlik",
    minStock: "Min sklad",
    price: "Narx",
    qrCode: "QR / Shtrix kod",
    scan: "Skan",
    unitsPerBox: "Qutidagi soni",
    unitName: "Birlik nomi",
    firm: "Firma",
    selectFirm: "Firma tanlang",
    noFirmsYet: "Firma qo'shilmagan",
    addFirm: "+ Yangi firma",
    firmName: "Firma nomi",
    address: "Manzil",
    phone: "Telefon",
    addedDate: "Qo'shilgan sana",
    totalOrders: "Jami orderlar",
    debt: "Qarz",
    noDebt: "Yo'q",
    info: "Info",
    pay: "Pay",
    history: "Tarix",
    totalDebt: "Umumiy qarz",
    totalPaid: "To'langan",
    totalAmount: "Jami summa",
    payAmount: "To'lov summasi",
    payAll: "Hammasi",
    note: "Izoh",
    payNote: "Naqd, bank...",
    noOrders: "Order yo'q",
    noHistory: "To'lov tarixi yo'q",
    newOrder: "+ Yangi order",
    selectProduct: "Mahsulot tanlang",
    quantity: "Soni",
    payStatus: "To'lov holati",
    totalPrice: "Jami summa",
    savedToStock: "Skladga qo'shildi",
    newRequest: "+ Yangi so'rov",
    transferRequest: "Transfer so'rovi",
    selectBranch: "Filial",
    addProduct: "+ Mahsulot qo'shish",
    transferNote: "Eslatma",
    send: "Yuborish",
    transferDetails: "Transfer tafsilotlari",
    requestedBy: "So'ragan",
    approvedBy: "Tasdiqlagan",
    noTransfers: "Transfer yo'q",
    recentTransfers: "Oxirgi transferlar",
    viewAll: "Barchasi",
    stockValue: "Sklad qiymati",
    productTypes: "Mahsulot turlari",
    totalStaff: "Jami xodim",
    orderDebt: "Order qarzi",
    myStock: "Skladim",
    myRequests: "So'rovlarim",
    waiting: "Kutilmoqda",
    firms: "Firmalar",
    branchStatus: "Filiallar",
    editStock: "Miqdorni o'zgartirish",
    currentQty: "Hozirgi",
    newQty: "Yangi miqdor",
    stockUpdated: "Sklad yangilandi",
    invalidQty: "Noto'g'ri miqdor",
    total: "Jami",
    branch: "Filial",
    date: "Sana",
  },
  ko: {
    dashboard: "대시보드",
    warehouse: "창고",
    transfers: "이동",
    orders: "주문",
    products: "상품",
    suppliers: "업체",
    logout: "로그아웃",
    language: "언어",
    uzbek: "우즈벡어",
    korean: "한국어",
    dark: "다크",
    light: "라이트",
    mode: "모드",
    loading: "로딩 중...",
    save: "저장",
    cancel: "취소",
    close: "닫기",
    edit: "수정",
    view: "보기",
    approve: "승인",
    reject: "거절",
    sending: "전송 중...",
    pending: "대기",
    approved: "승인됨",
    rejected: "거절됨",
    partial: "부분",
    paid: "완료",
    unpaid: "미결제",
    lowStock: "부족",
    medium: "주의",
    good: "양호",
    searchProduct: "상품 검색...",
    noProductsFound: "상품 없음",
    addNewProduct: "새 상품 추가",
    productName: "상품명",
    category: "카테고리",
    unit: "단위",
    minStock: "최소 재고",
    price: "가격",
    qrCode: "QR 코드",
    scan: "스캔",
    unitsPerBox: "박스당 수량",
    unitName: "단위명",
    firm: "업체",
    selectFirm: "업체 선택",
    noFirmsYet: "업체 없음",
    addFirm: "+ 새 업체",
    firmName: "업체명",
    address: "주소",
    phone: "전화",
    addedDate: "등록일",
    totalOrders: "총 주문",
    debt: "미수금",
    noDebt: "없음",
    info: "정보",
    pay: "결제",
    history: "내역",
    totalDebt: "총 미수금",
    totalPaid: "결제됨",
    totalAmount: "총 금액",
    payAmount: "결제 금액",
    payAll: "전액",
    note: "메모",
    payNote: "현금, 은행...",
    noOrders: "주문 없음",
    noHistory: "결제 내역 없음",
    newOrder: "+ 새 주문",
    selectProduct: "상품 선택",
    quantity: "수량",
    payStatus: "결제 상태",
    totalPrice: "총 금액",
    savedToStock: "창고에 추가됨",
    newRequest: "+ 새 요청",
    transferRequest: "이동 요청",
    selectBranch: "지점",
    addProduct: "+ 상품 추가",
    transferNote: "메모",
    send: "전송",
    transferDetails: "이동 상세",
    requestedBy: "요청자",
    approvedBy: "승인자",
    noTransfers: "이동 없음",
    recentTransfers: "최근 이동",
    viewAll: "전체",
    stockValue: "재고 금액",
    productTypes: "상품 종류",
    totalStaff: "전체 직원",
    orderDebt: "주문 미수금",
    myStock: "내 재고",
    myRequests: "내 요청",
    waiting: "대기",
    firms: "업체",
    branchStatus: "지점 현황",
    editStock: "재고 수량 수정",
    currentQty: "현재",
    newQty: "새 수량",
    stockUpdated: "재고 수정됨",
    invalidQty: "수량 오류",
    total: "합계",
    branch: "지점",
    date: "날짜",
  },
};

export const BRANCH_NAMES: Record<string, string> = {
  restaurant1: "Oshxona-1",
  restaurant2: "Oshxona-2",
  shop: "Do'kon",
  main: "Bosh Sklad",
};

export const BRANCH_ICONS: Record<string, string> = {
  restaurant1: "🍽️",
  restaurant2: "🍜",
  shop: "🏪",
  main: "🏭",
  superadmin: "🏭",
};

export const TRANSFER_STATUS_CONFIG = {
  pending: { c: "#f0a500", bg: "rgba(240,165,0,0.12)", l: "Kutilmoqda", i: "⏳" },
  approved: { c: "#3fb950", bg: "rgba(63,185,80,0.12)", l: "Tasdiqlandi", i: "✅" },
  rejected: { c: "#f85149", bg: "rgba(248,81,73,0.12)", l: "Rad etildi", i: "❌" },
};

export const PAY_STATUS_CONFIG = {
  paid: { c: "#3fb950", bg: "rgba(63,185,80,0.12)", l: "✅ To'langan" },
  unpaid: { c: "#f85149", bg: "rgba(248,81,73,0.12)", l: "❌ To'lanmagan" },
  partial: { c: "#f0a500", bg: "rgba(240,165,0,0.12)", l: "⏳ Qisman" },
};
